language: python

matrix:
  include:
    - python: "2.7"
    - python: "3.5"

cache:
  directories:
    - .pip_download_cache

env:
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"
    - GOOGLE_APPLICATION_CREDENTIALS=~/Netflix-Skunkworks/cloudaux/tests/gcp/fixtures/testkey.json

before_script:
  - python setup.py develop
  - pip install pytest
  - pip install mock
  - pip install coveralls

script:
  - coverage run -m py.test tests || exit 1

after_success:
  - coverage report
  - coveralls

notifications:
  email:
    - pkelley@netflix.com
    - mgrima@netflix.com